### ISSUE TITLE
i mean it's not a real issue BUT..

### ISSUE THREAD

**Issue by Xavier129** [richardletshacks/InstagramReposter#1]
Well, the bot works perfectly but i just want if it you can change _https://meme-api.herokuapp.com/gimme/dankmeme_ by **https://meme-api.herokuapp.com/gimme** only so i can share top posts from meirl,memes and dankmemes subreddits and also the hashtag to be **"?tag=dankmeme"** not **"?tag=meme"** only and upload and as a second release in jar 
I REALLY APPRECIATE YOUR WORK!

i'm saying this bcs i can't do it by myself since i'm newbie lmao 😅

**Comment by richardletshacks** [comment]
Thank you for your interest!
I'll probably just add settings to the setup regarding the hashtags, where you can specify what hashtags to use.
I can change the meme api to use all 3 subreddits, it just wasn't supposed to do this since I started creating the bot for my own and I dont really like all memes from memes or meirl.
A proper meme api will probably come in the next updates, stay tuned!

**Comment by Xavier129** [comment]
Hello again
I want to know how you keep running it like every barely an hour does it keep running even after shutting the pc lol or keeping the jar file running while the pc is on all the time bcs i want the same thing but turned out that after shutting down my pc the script stops aswell so is there a schedule trick that keeps the jar keeps working or something or using rdp or something!!
all i want is to run it all the time **non stop** is it possible !!
